development:
  adapter: postgresql
  database: technews_development
  encoding: utf8
  username: fred
  password:
  host: 127.0.0.1
  pool: 20

production:
  adapter: postgresql
  database: technews_development
  encoding: utf8
  username: fred
  password:
  host: 127.0.0.1
  pool: 20

test:
  adapter: postgresql
  database: technews_test
  encoding: utf8
  username: fred
  password:
  host: 127.0.0.1