development:
  access_key_id: 0KGT8PEVJR6ZFXZJK102
  secret_access_key: gJAgx90StWtkpzPNnF08fWLoMp5HgHd7K4PbMhk2
  bucket: technews
production:
  access_key_id: 0KGT8PEVJR6ZFXZJK102
  secret_access_key: gJAgx90StWtkpzPNnF08fWLoMp5HgHd7K4PbMhk2
  bucket: technews
test:
  access_key_id: 0KGT8PEVJR6ZFXZJK102
  secret_access_key: gJAgx90StWtkpzPNnF08fWLoMp5HgHd7K4PbMhk2
  bucket: technews-test